"""Alter table user enterprise nullable

Revision ID: cfedb5503391
Revises: f5f79aa0b10c
Create Date: 2025-04-23 14:52:45.153931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfedb5503391'
down_revision: Union[str, None] = 'f5f79aa0b10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'enterprise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'enterprise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
