"""alter table products

Revision ID: e39cdd95199d
Revises: 966380b6e6ca
Create Date: 2025-04-25 20:35:15.480210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39cdd95199d'
down_revision: Union[str, None] = '966380b6e6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('previous_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('month', sa.String(), nullable=True))
    op.add_column('products', sa.Column('initial_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('remaining_stock', sa.Integer(), nullable=True))
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'remaining_stock')
    op.drop_column('products', 'initial_stock')
    op.drop_column('products', 'month')
    op.drop_column('products', 'discount_percentage')
    op.drop_column('products', 'previous_price')
    # ### end Alembic commands ###
