"""Alter table products for description, price and stock

Revision ID: f5f79aa0b10c
Revises: 315f84826f9b
Create Date: 2025-04-23 14:49:07.395524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f79aa0b10c'
down_revision: Union[str, None] = '315f84826f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('usuarios', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'name')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
